//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amgl.launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdaterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdaterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amgl.launcher.UpdaterResources", typeof(UpdaterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 VERSIONINFO
        ///FILEVERSION ${Major},${Minor},${Build},${Revision}
        ///PRODUCTVERSION ${Major},${Minor},${Build},${Revision}
        ///FILEOS 0x4
        ///FILETYPE 0x1
        ///{
        ///	BLOCK &quot;StringFileInfo&quot;
        ///	{
        ///		BLOCK &quot;000004b0&quot;
        ///		{
        ///			VALUE &quot;Comments&quot;, &quot;${Comments}&quot;
        ///			VALUE &quot;CompanyName&quot;, &quot;${CompanyName}&quot;
        ///			VALUE &quot;FileDescription&quot;, &quot;${FileDescription}&quot;
        ///			VALUE &quot;FileVersion&quot;, &quot;${Major}.${Minor}.${Build}.${Revision}&quot;
        ///			VALUE &quot;InternalName&quot;, &quot;${InternalName}&quot;
        ///			VALUE &quot;LegalCopyright&quot;, &quot;${LegalCopyright}&quot;
        ///			VALUE &quot;LegalTradem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VersionTemplate {
            get {
                return ResourceManager.GetString("VersionTemplate", resourceCulture);
            }
        }
    }
}
